version: '3.3'

services:
  api:
    build: .
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis

  api_celery:
    build: .
    container_name: api_celery
    command: celery --app=challenge_greenole worker --loglevel=INFO -E
    volumes:
      - .:/usr/src/app
    depends_on: 
      - api
      - redis

  redis:
    image: redis:latest
    container_name: redis