# Generated by Django 4.1.4 on 2022-12-27 23:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateMeasurementData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_id', models.BigIntegerField(verbose_name='ID Sensor')),
                ('measured_at', models.DateTimeField(verbose_name='Measured at')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'db_table': 'duplicate_measurement_data',
            },
        ),
        migrations.CreateModel(
            name='MeasurementData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_id', models.BigIntegerField(verbose_name='ID Sensor')),
                ('measured_at', models.DateTimeField(verbose_name='Measured at')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'db_table': 'measurement_data',
            },
        ),
    ]
